### ISSUE TITLE
Unable to update to mortein-sdk v0.3.0 due to authentication issue

### ISSUE THREAD

**Issue by Amelia-C5** [deco3801-mortein/frontend#20]
In the package_registry_setup branch, this happens when I attempt to update the mortein-sdk package:
<img width="781" alt="Screenshot 2024-09-30 230226" src="https://github.com/user-attachments/assets/ca28f997-4af7-4db8-a76b-d671527e87d4">

It seems like I am definitely authenticated though. When I authenticate using npm login to verify if my token was still working it appears to accept it:
<img width="581" alt="Screenshot 2024-09-30 230626" src="https://github.com/user-attachments/assets/ebceddba-52e2-46f9-9015-7c1e24cd6b55">

npm install and npm clean-install also still works.

**Comment by willsawyerrrr** [comment]
What does the complete log contain?

**Comment by willsawyerrrr** [comment]
If you edit the `package.json` file, bump the version to `0.3.0` and run `npm install`, do you get the same problem?

**Comment by willsawyerrrr** [comment]
Try clearing your `npm` cache with `npm cache clean --force` and then `npm install` again to confirm you are authenticated. Your token may no longer be valid, but `npm` may have cached the SDK, so it doesn't need to authenticate to the GitHub `npm` registry to install.

**Comment by willsawyerrrr** [comment]
> If you edit the `package.json` file, bump the version to `0.3.0` and run `npm install`, do you get the same problem?

This worked for me.

**Comment by willsawyerrrr** [comment]
`npm` update won't bump from `0.1.0` to `0.3.0` since changes to the minor version is considered a breaking change with major version `0`.

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
> \- https://semver.org/#spec-item-4

I'll release the SDK with major version 1 to ensure further versions are more easy to consume.

**Comment by Amelia-C5** [comment]
> If you edit the `package.json` file, bump the version to `0.3.0` and run `npm install`, do you get the same problem?

Yes. I have tried that. It still doesn't like the authentication.

**Comment by Amelia-C5** [comment]
> > If you edit the `package.json` file, bump the version to `0.3.0` and run `npm install`, do you get the same problem?
> 
> This worked for me.

Okay. I will try to clear the cache and see if my token still works.

**Comment by willsawyerrrr** [comment]
According to your `.npmrc`, you're authenticating with the `NPM_AUTH` environment variable.

Without sharing its value here because its a credential, can you confirm that environment variable is populated by running `echo $NPM_AUTH`?

**Comment by willsawyerrrr** [comment]
> I'll release the SDK with major version 1 to ensure further versions are more easy to consume.

This has now been released. You should upgrade to `1.0.0` instead of `0.3.0`.

**Comment by Amelia-C5** [comment]
> What does the complete log contain?

Do you mean the password? I just used my token for the password. I think that's what the docs said to do.

**Comment by willsawyerrrr** [comment]
The first screenshot in your issue mentions a complete log of the `npm` command run.

The information contained in that run could be useful for diagnosing the problem here.

**Comment by Amelia-C5** [comment]
I figured out the problem. The .npmrc file was not reading my environment variable for the token. I put the token directly in the .npmrc file and the install worked. I cannot put this in the repository but I am unsure how to make the environment variable work on my computer.

**Comment by willsawyerrrr** [comment]
In order to have the environment variable included in your devcontainer, you need to change your devcontainer config to use a Docker Compose file instead of just an image.

You can copy the [Docker Compose file](https://github.com/deco3801-mortein/api/tree/main/.devcontainer/docker-compose.yaml) from the API repo if you'd like - you'll just have to:
- update the image for the `devcontainer` service to be the one you're currently using;
- change the `api` component of the `devcontainer` service's volume to `frontend`; and
- remove the `database` service.

Once you've added the Docker Compose file, replace the `image` key in your `.devcontainer/devcontainer.json` file with the `dockerComposeFile`, `service` and `workspaceFolder` keys in the API's `.devcontainer/devcontainer.json` file, ensuring you update the `workspaceFolder` in the same way you did the volume.
