### ISSUE TITLE
API connection issues

### ISSUE THREAD

**Issue by Amelia-C5** [deco3801-mortein/frontend#21]
Code:
![Screenshot (232)](https://github.com/user-attachments/assets/f4144c0c-0a8a-4e02-9163-f4c1674b4373)

Errors:
![Screenshot (231)](https://github.com/user-attachments/assets/3c33576f-f58a-400d-a24a-c05038cd069e)

**Comment by willsawyerrrr** [comment]
Can you try to minimise the scope of this to isolate the problem?

You're currently making the API request in the scope of a React application and there are multiple errors occurring, including one directly related to React, so it's not clear that the API is responsible for this problem.

Once you can minimise the scope of the problem to ensure that API is directly and solely responsible, create an issue on the API repo - not this repo - and I'll investigate.
